// GENERATED by backend/tools/gen_wallloop_fixtures.py — do not edit.
// Pins WallLoop.swift (the on-device port) to the backend's Decision 34
// open-edge detection across every archived real scan. A failure here
// means the two implementations disagree about a real room.
import XCTest
import simd
@testable import BuildPilot

final class WallLoopRealScanTests: XCTestCase {
    private func wall(_ x0: Double, _ y0: Double, _ z0: Double,
                      _ tx: Double, _ ty: Double, _ tz: Double,
                      w: Double, h: Double) -> (simd_float4x4, SIMD3<Float>) {
        var t = matrix_identity_float4x4
        t.columns.0 = SIMD4(Float(x0), Float(y0), Float(z0), 0)
        t.columns.3 = SIMD4(Float(tx), Float(ty), Float(tz), 1)
        return (t, SIMD3(Float(w), Float(h), 0))
    }

    private func assess(_ walls: [(simd_float4x4, SIMD3<Float>)])
        -> (open: Int, dups: [String], status: WallLoopStatus) {
        let f = WallLoop.footprints(
            transforms: walls.map(\.0), dimensions: walls.map(\.1))
        return (WallLoop.openEnds(f).count,
                WallLoop.duplicates(f).keys.sorted(),
                WallLoop.assess(f))
    }

    func test_visit_20260710_124630_60c503() {  // backend: complete
        let walls = [
            wall(1.000000, 0.000000, 0.000000, 0.000000, 1.250000, -1.500000, w: 5.000000, h: 2.500000),
            wall(1.000000, 0.000000, 0.000000, 0.000000, 1.250000, 1.500000, w: 5.000000, h: 2.500000),
            wall(0.000000, 0.000000, 1.000000, -2.500000, 1.250000, 0.000000, w: 3.000000, h: 2.500000),
            wall(0.000000, 0.000000, 1.000000, 2.500000, 1.250000, 0.000000, w: 3.000000, h: 2.500000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 0)
        XCTAssertEqual(result.dups, [])
        XCTAssertEqual(result.status, .closed(wallCount: walls.count))
    }

    func test_visit_20260710_135715_4f59e5() {  // backend: incomplete
        let walls = [
            wall(0.998965, 0.000000, 0.045485, -3.315020, 0.568767, -3.801624, w: 5.349543, h: 2.382129),
            wall(-0.998965, 0.000000, -0.045485, -3.119360, 0.568767, 0.459443, w: 4.549276, h: 2.382129),
            wall(-0.998965, 0.000000, -0.045485, -6.004684, 0.568767, -0.872604, w: 1.336575, h: 2.382129),
            wall(0.045485, 0.000000, -0.998965, -5.364366, 0.568767, -0.243113, w: 1.199429, h: 2.382129),
            wall(0.101863, 0.000000, 0.994798, -0.606126, 0.568767, -3.319687, w: 0.724316, h: 2.382129),
            wall(-0.045485, 0.000000, 0.998965, -0.589757, 0.568767, -2.508717, w: 0.902326, h: 2.382129),
            wall(0.982785, 0.000000, 0.184754, -0.647779, 0.568767, -2.974179, w: 0.159838, h: 2.382129),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 4)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260710_142055_5a2356() {  // backend: incomplete
        let walls = [
            wall(-0.242739, 0.000000, 0.970092, 3.133290, -0.310908, -1.593197, w: 1.041797, h: 2.340000),
            wall(0.970092, 0.000000, 0.242739, 0.221134, -0.310908, -2.858843, w: 6.264561, h: 2.340000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260710_142622_23d40d() {  // backend: incomplete
        let walls = [
            wall(0.993790, 0.000000, 0.111273, 1.107721, 0.156302, -3.650362, w: 1.841021, h: 2.340000),
            wall(0.371673, 0.000000, -0.928364, 0.024701, 0.156302, -3.355826, w: 0.888534, h: 2.340000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260710_160129_df82ec() {  // backend: incomplete
        let walls = [
            wall(0.991269, 0.000000, 0.131858, 1.098718, -0.417292, -2.703231, w: 6.493971, h: 2.370000),
            wall(-0.131858, 0.000000, 0.991269, 4.271164, -0.417292, -1.927854, w: 0.700589, h: 2.370000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_060326_b23c4c() {  // backend: incomplete
        let walls = [
            wall(0.198210, 0.000000, 0.980160, 2.912124, 0.328809, -4.207876, w: 5.428517, h: 2.325000),
            wall(-0.970705, 0.000000, 0.240273, 2.160580, 0.328809, -1.228279, w: 2.656905, h: 2.325000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_064849_2d4e42() {  // backend: incomplete
        let walls = [
            wall(0.994400, 0.000000, 0.105684, -3.157002, 0.529079, -4.026143, w: 5.287930, h: 2.340000),
            wall(-0.105684, 0.000000, 0.994400, -0.567596, 0.529079, -3.372683, w: 0.752280, h: 2.340000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_071528_1c8239() {  // backend: incomplete
        let walls = [
            wall(0.999825, 0.000000, 0.018689, 0.591202, 0.495821, -3.731748, w: 1.754083, h: 2.358000),
            wall(-0.999825, 0.000000, -0.018689, 0.841126, 0.495821, 0.646596, w: 1.090667, h: 2.358000),
            wall(-0.018689, 0.000000, 0.999825, 1.427227, 0.495821, -1.529285, w: 4.372909, h: 2.358000),
            wall(0.018689, 0.000000, -0.999825, -0.760992, 0.495821, -2.357170, w: 2.652589, h: 2.358000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 4)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_072128_4f23cd() {  // backend: incomplete
        let walls = [
            wall(0.999585, 0.000000, 0.028796, -3.233096, -0.314579, -3.184098, w: 5.281837, h: 2.325000),
            wall(-0.028796, 0.000000, 0.999585, -0.610119, -0.314579, -2.523290, w: 1.170003, h: 2.325000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_074932_82401e() {  // backend: incomplete
        let walls = [
            wall(0.994756, 0.000000, 0.102275, -2.950600, 0.627260, -3.891015, w: 5.252966, h: 2.340000),
            wall(0.999750, 0.000000, 0.022369, 1.190837, 0.627260, -3.589571, w: 1.302149, h: 2.340000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 4)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_075153_501f70() {  // backend: incomplete
        let walls = [
            wall(0.994651, 0.000000, 0.103295, -0.549168, -0.287535, -2.267520, w: 5.375125, h: 2.385000),
            wall(-0.103295, 0.000000, 0.994651, 1.995420, -0.287535, -0.751619, w: 2.489897, h: 2.385000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_081400_afa5ba() {  // backend: incomplete
        let walls = [
            wall(-0.176399, 0.000000, 0.984319, 3.489001, -0.174112, -2.732020, w: 6.358752, h: 2.355000),
            wall(-0.984319, 0.000000, -0.176399, 2.154311, -0.174112, 0.258818, w: 1.572362, h: 2.355000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_085735_01e367() {  // backend: incomplete
        let walls = [
            wall(0.944666, 0.000000, -0.328033, -0.846332, -0.364260, -2.165236, w: 5.650466, h: 2.325000),
            wall(0.256281, 0.000000, 0.966602, 1.957965, -0.364260, -2.581348, w: 1.056604, h: 2.325000),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260711_100228_ccd8c4() {  // backend: incomplete
        let walls = [
            wall(-0.167554, 0.000000, 0.985863, 0.981992, -0.382019, -1.248224, w: 1.656281, h: 2.363845),
            wall(0.985863, 0.000000, 0.167554, -1.650265, -0.382019, -2.535610, w: 5.621501, h: 2.363845),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

    func test_visit_20260821_082357_e7241a() {  // backend: incomplete
        let walls = [
            wall(0.247319, 0.000000, -0.968934, -2.130405, -0.426364, -1.462763, w: 1.036109, h: 2.477143),
            wall(0.968934, 0.000000, 0.247319, 0.858395, -0.426364, -1.234540, w: 5.904789, h: 2.477143),
        ]
        let result = assess(walls)
        XCTAssertEqual(result.open, 2)
        XCTAssertEqual(result.dups, [])
    }

}