"""Session-directory storage (docs/DECISIONS.md, Decision 11).

Each visit is a self-contained folder:

    sessions/<session_id>/
        session.json        # the Session record (this file is the source of truth)
        room.json           # CapturedRoom JSON, verbatim from the phone
        audio.m4a           # visit audio (optional)
        transcript.txt      # written by the transcription stage
        estimate.json       # written by the estimation stage (also inside session.json)

No database. Replayable, diffable, explainable.
"""

from __future__ import annotations

import json
import secrets
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

from buildpilot.models.session import (
    AudioCapture,
    RoomScanCapture,
    Session,
    SessionStatus,
)

ROOM_SCAN_FILE = "room.json"
AUDIO_FILE = "audio.m4a"
SESSION_FILE = "session.json"
TRANSCRIPT_FILE = "transcript.txt"


class SessionStore:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def new_session_id(self) -> str:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        return f"visit-{stamp}-{secrets.token_hex(3)}"

    def session_dir(self, session_id: str) -> Path:
        # session ids are generated by the server; reject anything path-like
        if "/" in session_id or "\\" in session_id or ".." in session_id:
            raise ValueError(f"Invalid session id: {session_id!r}")
        return self.root / session_id

    def create_session(
        self,
        room_scan_bytes: bytes,
        audio_bytes: Optional[bytes],
        capture_device: str = "iphone",
    ) -> Session:
        session_id = self.new_session_id()
        directory = self.session_dir(session_id)
        directory.mkdir(parents=True)

        (directory / ROOM_SCAN_FILE).write_bytes(room_scan_bytes)
        room_scan = RoomScanCapture(
            file_name=ROOM_SCAN_FILE, size_bytes=len(room_scan_bytes)
        )

        audio = None
        if audio_bytes:
            (directory / AUDIO_FILE).write_bytes(audio_bytes)
            audio = AudioCapture(file_name=AUDIO_FILE, size_bytes=len(audio_bytes))

        now = datetime.now(timezone.utc)
        session = Session(
            session_id=session_id,
            status=SessionStatus.IN_PROGRESS,
            created_at=now,
            updated_at=now,
            capture_device=capture_device,
            room_scan=room_scan,
            audio=audio,
        )
        self.save(session)
        return session

    def save(self, session: Session) -> None:
        path = self.session_dir(session.session_id) / SESSION_FILE
        path.write_text(session.model_dump_json(indent=2))

    def load(self, session_id: str) -> Optional[Session]:
        path = self.session_dir(session_id) / SESSION_FILE
        if not path.exists():
            return None
        return Session.model_validate_json(path.read_text())

    def load_room_scan(self, session: Session) -> Dict[str, Any]:
        if session.room_scan is None:
            raise FileNotFoundError("Session has no room scan")
        path = self.session_dir(session.session_id) / session.room_scan.file_name
        return json.loads(path.read_text())

    def audio_path(self, session: Session) -> Optional[Path]:
        if session.audio is None:
            return None
        return self.session_dir(session.session_id) / session.audio.file_name

    def write_artifact(self, session: Session, file_name: str, content: str) -> None:
        (self.session_dir(session.session_id) / file_name).write_text(content)
