#!/usr/bin/env python3
"""Generate WallLoopRealScanTests.swift from the real-scan fixtures.

The iPhone's WallLoop.swift is a port of the backend's Decision 34 open-edge
detection. Ports drift; this pins them together: for every archived real scan
the generated Swift test feeds the raw wall transforms to WallLoop and asserts
it finds exactly the open ends and duplicate walls the backend found.

Rerun after changing either side:
    ../.venv/bin/python tools/gen_wallloop_fixtures.py   (from backend/)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # backend/ on path

from buildpilot.pipelines.measurement import RoomPlanMeasurementEngine, _transform_columns

BACKEND = Path(__file__).resolve().parents[1]
SCANS = sorted((BACKEND / "tests" / "fixtures" / "real_scans").glob("visit-*.json"))
OUT = BACKEND.parent / "iphone" / "BuildPilot" / "Tests" / "WallLoopRealScanTests.swift"

engine = RoomPlanMeasurementEngine()

cases = []
for path in SCANS:
    raw = json.loads(path.read_text())
    room = raw.get("room_scan", raw)
    m = engine.measure(room)
    completeness = m.completeness
    expected_open = len(completeness.open_edges) if completeness else 0
    expected_dups = sorted(w.wall_id for w in m.walls if w.duplicate_of)
    walls = []
    for wall in room.get("walls") or []:
        cols = _transform_columns(wall)
        dims = wall.get("dimensions") or []
        if cols is None or len(dims) < 2:
            continue  # backend skips unparseable walls; so does the port
        walls.append((cols[0], cols[3], float(dims[0]), float(dims[1])))
    cases.append((path.stem, walls, expected_open, expected_dups,
                  completeness.status if completeness else "n/a"))

lines = [
    "// GENERATED by backend/tools/gen_wallloop_fixtures.py — do not edit.",
    "// Pins WallLoop.swift (the on-device port) to the backend's Decision 34",
    "// open-edge detection across every archived real scan. A failure here",
    "// means the two implementations disagree about a real room.",
    "import XCTest",
    "import simd",
    "@testable import BuildPilot",
    "",
    "final class WallLoopRealScanTests: XCTestCase {",
    "    private func wall(_ x0: Double, _ y0: Double, _ z0: Double,",
    "                      _ tx: Double, _ ty: Double, _ tz: Double,",
    "                      w: Double, h: Double) -> (simd_float4x4, SIMD3<Float>) {",
    "        var t = matrix_identity_float4x4",
    "        t.columns.0 = SIMD4(Float(x0), Float(y0), Float(z0), 0)",
    "        t.columns.3 = SIMD4(Float(tx), Float(ty), Float(tz), 1)",
    "        return (t, SIMD3(Float(w), Float(h), 0))",
    "    }",
    "",
    "    private func assess(_ walls: [(simd_float4x4, SIMD3<Float>)])",
    "        -> (open: Int, dups: [String], status: WallLoopStatus) {",
    "        let f = WallLoop.footprints(",
    "            transforms: walls.map(\\.0), dimensions: walls.map(\\.1))",
    "        return (WallLoop.openEnds(f).count,",
    "                WallLoop.duplicates(f).keys.sorted(),",
    "                WallLoop.assess(f))",
    "    }",
    "",
]

for stem, walls, expected_open, expected_dups, status in cases:
    name = stem.replace("-", "_")
    lines.append(f"    func test_{name}() {{  // backend: {status}")
    lines.append("        let walls = [")
    for c0, c3, w, h in walls:
        lines.append(
            f"            wall({c0[0]:.6f}, {c0[1]:.6f}, {c0[2]:.6f}, "
            f"{c3[0]:.6f}, {c3[1]:.6f}, {c3[2]:.6f}, w: {w:.6f}, h: {h:.6f}),"
        )
    lines.append("        ]")
    lines.append("        let result = assess(walls)")
    lines.append(f"        XCTAssertEqual(result.open, {expected_open})")
    dups = ", ".join(f'"{d}"' for d in expected_dups)
    lines.append(f"        XCTAssertEqual(result.dups, [{dups}])")
    if status == "complete" and expected_open == 0:
        lines.append("        XCTAssertEqual(result.status, .closed(wallCount: walls.count))")
    lines.append("    }")
    lines.append("")

lines.append("}")
OUT.write_text("\n".join(lines))
print(f"wrote {OUT.relative_to(BACKEND.parent)}: {len(cases)} scans, "
      f"{sum(len(w) for _, w, *_ in cases)} walls")
